2021-02-04 16:40:04 - root - INFO: - 等待元素: id,com.nowcoder.app.florida:id/gotoLoginView
2021-02-04 16:40:05 - root - INFO: - 等待结束，等待时长为：0:00:00.906002
2021-02-04 16:40:05 - root - INFO: - 查找元素：id,com.nowcoder.app.florida:id/gotoLoginView
2021-02-04 16:40:05 - root - INFO: - 点击元素：id,com.nowcoder.app.florida:id/gotoLoginView
2021-02-04 16:40:07 - root - INFO: - 等待元素: id,com.nowcoder.app.florida:id/btn_switch_veritype
2021-02-04 16:40:07 - root - INFO: - 等待结束，等待时长为：0:00:00.096660
2021-02-04 16:40:07 - root - INFO: - 查找元素：id,com.nowcoder.app.florida:id/btn_switch_veritype
2021-02-04 16:40:07 - root - INFO: - 点击元素：id,com.nowcoder.app.florida:id/btn_switch_veritype
2021-02-04 16:40:07 - root - INFO: - 等待元素: id,com.nowcoder.app.florida:id/goto_oversea_page
2021-02-04 16:40:08 - root - INFO: - 等待结束，等待时长为：0:00:00.633458
2021-02-04 16:40:08 - root - INFO: - 查找元素：id,com.nowcoder.app.florida:id/goto_oversea_page
2021-02-04 16:40:08 - root - INFO: - 点击元素：id,com.nowcoder.app.florida:id/goto_oversea_page
2021-02-04 16:40:08 - root - INFO: - 查找元素：id,com.nowcoder.app.florida:id/country_textview
2021-02-04 16:40:09 - root - INFO: - 点击元素：id,com.nowcoder.app.florida:id/country_textview
2021-02-04 16:40:09 - root - INFO: - 等待元素: id,com.nowcoder.app.florida:id/item_relative
2021-02-04 16:40:11 - root - INFO: - 等待结束，等待时长为：0:00:01.848414
2021-02-04 16:40:11 - root - INFO: - 点击元素：id,com.nowcoder.app.florida:id/item_relative
2021-02-04 16:40:11 - root - INFO: - 等待元素: id,com.nowcoder.app.florida:id/loginnumber_phones
2021-02-04 16:40:12 - root - INFO: - 等待结束，等待时长为：0:00:01.198590
2021-02-04 16:40:12 - root - INFO: - 查找元素：id,com.nowcoder.app.florida:id/loginnumber_phones
2021-02-04 16:40:12 - root - INFO: - 输入数据：5678250990
2021-02-04 16:40:12 - root - INFO: - 查找元素：id,com.nowcoder.app.florida:id/loginnumber_password
2021-02-04 16:40:13 - root - INFO: - 输入数据：Aa112211
2021-02-04 16:40:13 - root - INFO: - 查找元素：id,com.nowcoder.app.florida:id/go_numberlogin
2021-02-04 16:40:13 - root - INFO: - 点击元素：id,com.nowcoder.app.florida:id/go_numberlogin
2021-02-04 16:40:14 - root - INFO: - 等待元素: id,com.nowcoder.app.florida:id/tab_profile
2021-02-04 16:40:25 - root - INFO: - 等待结束，等待时长为：0:00:11.615668
2021-02-04 16:40:25 - root - INFO: - 查找元素：id,com.nowcoder.app.florida:id/tab_profile
2021-02-04 16:40:26 - root - INFO: - 点击元素：id,com.nowcoder.app.florida:id/tab_profile
2021-02-04 16:40:26 - root - ERROR: - 元素点击操作失败：id,com.nowcoder.app.florida:id/tab_profile
Traceback (most recent call last):
  File "D:\Projects\PythonAppium\Common\basepage.py", line 88, in ele_click
    ele.click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET

2021-02-04 16:40:26 - root - INFO: - 等待元素: id,com.nowcoder.app.florida:id/loginnumber_phones
2021-02-04 16:40:26 - root - ERROR: - 等待 id,com.nowcoder.app.florida:id/loginnumber_phones 元素可见失败！！！
Traceback (most recent call last):
  File "D:\Projects\PythonAppium\Common\basepage.py", line 63, in wait_eleVisible
    WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located(loc))
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\webdriver.py", line 281, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET

2021-02-04 16:40:27 - root - INFO: - 等待元素: id,com.nowcoder.app.florida:id/loginnumber_phones
2021-02-04 16:40:27 - root - ERROR: - 等待 id,com.nowcoder.app.florida:id/loginnumber_phones 元素可见失败！！！
Traceback (most recent call last):
  File "D:\Projects\PythonAppium\Common\basepage.py", line 63, in wait_eleVisible
    WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located(loc))
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\webdriver.py", line 281, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET

2021-02-04 16:40:27 - root - INFO: - 等待元素: id,com.nowcoder.app.florida:id/loginnumber_phones
2021-02-04 16:40:27 - root - ERROR: - 等待 id,com.nowcoder.app.florida:id/loginnumber_phones 元素可见失败！！！
Traceback (most recent call last):
  File "D:\Projects\PythonAppium\Common\basepage.py", line 63, in wait_eleVisible
    WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located(loc))
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\webdriver.py", line 281, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET

2021-02-04 16:40:27 - root - INFO: - 等待元素: id,com.nowcoder.app.florida:id/loginnumber_phones
2021-02-04 16:40:27 - root - ERROR: - 等待 id,com.nowcoder.app.florida:id/loginnumber_phones 元素可见失败！！！
Traceback (most recent call last):
  File "D:\Projects\PythonAppium\Common\basepage.py", line 63, in wait_eleVisible
    WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located(loc))
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\webdriver.py", line 281, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET

2021-02-04 16:40:27 - root - INFO: - 等待元素: id,com.nowcoder.app.florida:id/loginnumber_phones
2021-02-04 16:40:27 - root - ERROR: - 等待 id,com.nowcoder.app.florida:id/loginnumber_phones 元素可见失败！！！
Traceback (most recent call last):
  File "D:\Projects\PythonAppium\Common\basepage.py", line 63, in wait_eleVisible
    WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located(loc))
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\webdriver.py", line 281, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Program Files\Python36\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET

